// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgXb2O0YV7CPJyhPX7tmtfrSPFJ9jvJLg',
    appId: '1:138493900131:web:55a06a4e7c9879954b8f56',
    messagingSenderId: '138493900131',
    projectId: 'ems-protocols-432c3',
    authDomain: 'ems-protocols-432c3.firebaseapp.com',
    storageBucket: 'ems-protocols-432c3.appspot.com',
    measurementId: 'G-NRR1JEYFT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC642ZZwX7gjloHdamedHdYmdJkjN7ONKc',
    appId: '1:138493900131:android:a6b11f4bd4469e294b8f56',
    messagingSenderId: '138493900131',
    projectId: 'ems-protocols-432c3',
    storageBucket: 'ems-protocols-432c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9dfopNnIF3ibXC7d4AeAD-gHo7Wd9N7I',
    appId: '1:138493900131:ios:e1f36a4d899e5f594b8f56',
    messagingSenderId: '138493900131',
    projectId: 'ems-protocols-432c3',
    storageBucket: 'ems-protocols-432c3.appspot.com',
    iosClientId: '138493900131-2l4gkn110h2f99aastboi5o8h3tpdcob.apps.googleusercontent.com',
    iosBundleId: 'com.luke.emsprotocols',
  );
}
